name: connection
description: "Connection - a real-time privacy-first couple messaging app."
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.12.1
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.7.1
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.0.0
  cloudinary_public: ^0.23.1
  image_picker: ^1.1.2
  record: ^7.1.1
  path_provider: ^2.1.6
  file_picker: ^8.3.7
  audioplayers: ^6.8.1
  url_launcher: ^6.3.2
  cryptography: ^2.9.0
  geolocator: ^14.0.2
  local_auth: ^3.0.2
  flutter_secure_storage: ^9.2.4
  video_player: ^2.9.5
  flutter_webrtc: ^0.12.7
  shared_preferences: ^2.3.3
  connectivity_plus: ^6.1.1
  flutter_image_compress: ^2.3.0
  http: ^1.2.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  path_provider_windows: ^2.3.0
  ffi: ^2.2.0

flutter:
  uses-material-design: true
